# Generated by Django 4.1.3 on 2022-11-09 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_bistro', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Menu_items',
            new_name='Menu_item',
        ),
    ]
