# Generated by Django 4.1.3 on 2022-11-09 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_bistro', '0002_rename_menu_items_menu_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category_id',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='cuisine_id',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='menu_item',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
