# Generated by Django 4.1.3 on 2022-11-09 23:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend_bistro', '0004_rename_cuisine_id_category_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Categorie',
        ),
        migrations.AlterField(
            model_name='menu_item',
            name='cuisine_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend_bistro.cuisine'),
        ),
    ]
