# Generated by Django 4.1.3 on 2022-11-10 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend_bistro', '0006_rename_categorie_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu_item',
            name='category_id',
        ),
        migrations.RemoveField(
            model_name='menu_item',
            name='cuisine_id',
        ),
        migrations.AddField(
            model_name='menu_item',
            name='category',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend_bistro.category'),
        ),
        migrations.AddField(
            model_name='menu_item',
            name='cuisine',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend_bistro.cuisine'),
        ),
    ]
