# Generated by Django 4.1.3 on 2022-11-10 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_bistro', '0007_remove_menu_item_category_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu_item',
            name='price',
            field=models.FloatField(null=True),
        ),
    ]
